# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fabio Gottlicher's blog
email: g.fabio.cz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog and project presentation website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fabiocz.github.io" # the base hostname & protocol for your site
twitter_username: FabioG_CZ
github_username:  FabioCZ

# Build settings
markdown: kramdown
